# Generated by Django 6.0.5 on 2026-05-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leistung', models.CharField(choices=[('entruempelung', 'Entrümpelung'), ('sanierung', 'Sanierung & Reparatur'), ('komplett', 'Komplett-Paket (Entrümpelung + Sanierung)'), ('sonstiges', 'Sonstiges')], max_length=50, verbose_name='Leistungsart')),
                ('zusatz_info', models.TextField(blank=True, verbose_name='Zusätzliche Informationen')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer')),
                ('adresse', models.CharField(blank=True, max_length=500, verbose_name='Adresse des Objekts')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anfrage',
                'verbose_name_plural': 'Anfragen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
