# Generated by Django 6.0.5 on 2026-05-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anfrage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreisAngebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('leistung_label', models.CharField(max_length=300, verbose_name='Leistung')),
                ('groesse_label', models.CharField(blank=True, max_length=500, verbose_name='Größe / Positionen')),
                ('pmin', models.PositiveIntegerField(verbose_name='Preis min (€)')),
                ('pmax', models.PositiveIntegerField(verbose_name='Preis max (€)')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('erinnerung_gesendet', models.BooleanField(default=False, verbose_name='Erinnerung gesendet')),
            ],
            options={
                'verbose_name': 'Preisangebot',
                'verbose_name_plural': 'Preisangebote',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
