# Generated by Django 6.0.5 on 2026-08-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_aktuellesbild_typ_bild'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktuellesbild',
            name='bildtext',
            field=models.CharField(blank=True, default='', help_text='Was ist zu sehen? Mit Ort und Leistung, z. B. "Haushaltsauflösung in Halle-Neustadt, Küche vor der Räumung".', max_length=180, verbose_name='Bildbeschreibung'),
        ),
    ]
