# Generated by Django 6.0.5 on 2026-08-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aktuellesbild_bildtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('wert', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Durchschnitt')),
                ('anzahl', models.PositiveIntegerField(verbose_name='Anzahl Bewertungen')),
                ('place_id', models.CharField(blank=True, max_length=200)),
                ('profil_url', models.URLField(blank=True, max_length=500)),
                ('geprueft_am', models.DateTimeField(verbose_name='Zuletzt abgeglichen')),
            ],
            options={
                'verbose_name': 'Google-Bewertung (Gesamtstand)',
                'verbose_name_plural': 'Google-Bewertung (Gesamtstand)',
            },
        ),
        migrations.CreateModel(
            name='GoogleRezension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quelle_id', models.CharField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Autor')),
                ('initialen', models.CharField(max_length=4)),
                ('sterne', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('profil_url', models.URLField(blank=True, max_length=500)),
                ('relativ', models.CharField(blank=True, max_length=60, verbose_name='Zeitangabe („vor 3 Monaten“)')),
                ('veroeffentlicht', models.DateTimeField(blank=True, null=True)),
                ('sichtbar', models.BooleanField(default=True)),
                ('zuletzt_gesehen', models.DateTimeField()),
                ('angelegt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Google-Rezension',
                'verbose_name_plural': 'Google-Rezensionen',
                'ordering': ['-veroeffentlicht', '-angelegt_am'],
            },
        ),
    ]
