# Generated by Django 6.0.5 on 2026-08-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_googlebewertung_googlerezension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlerezension',
            options={'ordering': [models.OrderBy(models.F('veroeffentlicht'), descending=True, nulls_last=True), '-angelegt_am'], 'verbose_name': 'Google-Rezension', 'verbose_name_plural': 'Google-Rezensionen'},
        ),
    ]
