# Generated by Django 6.0.5 on 2026-09-05 23:44
#
# P8/C2 und C3: Model ``Bewerbung`` und die beiden Versandfelder.
#
# ⚠ DER ZWEITE TEIL DIESER MIGRATION IST DER WICHTIGE.
#
# ``mail_gesendet`` bekommt den Vorgabewert ``False``. Fuer jede Zeile, die
# beim Deploy schon in der Tabelle steht, hiesse das woertlich: "die
# Benachrichtigung ist nie hinausgegangen". Der Nachzuegler aus C3 nimmt alles
# mit ``mail_gewollt=True`` und ``mail_gesendet=False``, das juenger ist als
# ``views._NACHZUEGLER_MAX_TAGE`` (7 Tage) - er wuerde beim ersten
# Scheduler-Lauf nach dem Deploy **jede Anfrage, jedes Preisangebot und jede
# Kooperationsanfrage der letzten Woche erneut zustellen**, an den Betrieb und
# an die Kunden.
#
# Deshalb wird der Altbestand einmalig auf ``mail_gesendet=True`` gesetzt. Das
# ist keine Behauptung, dass die Mails ankamen - sie ist unpruefbar, weil es
# vorher gar keinen Vermerk gab. Es ist die Aussage: **Diese Zeilen sind unter
# der alten Regel entstanden und werden nicht rueckwirkend behandelt.** Der
# Nachzuegler gilt ab hier.

from django.db import migrations, models


def _altbestand_als_erledigt_markieren(apps, schema_editor):
    """Alles, was es schon gibt, gilt als versandt - Begruendung im Dateikopf."""
    for name in ('Anfrage', 'PreisAngebot', 'Kooperationsanfrage'):
        apps.get_model('core', name).objects.update(mail_gesendet=True)


def _zurueck(apps, schema_editor):
    """Nichts zu tun - die Felder verschwinden beim Ruecklauf ohnehin."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_googlerezension_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bewerbung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_gewollt', models.BooleanField(default=True, verbose_name='Benachrichtigung vorgesehen')),
                ('mail_gesendet', models.BooleanField(default=False, verbose_name='Benachrichtigung gesendet')),
                ('stelle', models.CharField(help_text='Slug der Stellenseite oder die frei eingegebene Wunschposition von /jobs/.', max_length=300, verbose_name='Stelle')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer')),
                ('nachricht', models.TextField(blank=True, verbose_name='Nachricht')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bewerbung',
                'verbose_name_plural': 'Bewerbungen',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.AddField(
            model_name='anfrage',
            name='mail_gesendet',
            field=models.BooleanField(default=False, verbose_name='Benachrichtigung gesendet'),
        ),
        migrations.AddField(
            model_name='anfrage',
            name='mail_gewollt',
            field=models.BooleanField(default=True, verbose_name='Benachrichtigung vorgesehen'),
        ),
        migrations.AddField(
            model_name='kooperationsanfrage',
            name='mail_gesendet',
            field=models.BooleanField(default=False, verbose_name='Benachrichtigung gesendet'),
        ),
        migrations.AddField(
            model_name='kooperationsanfrage',
            name='mail_gewollt',
            field=models.BooleanField(default=True, verbose_name='Benachrichtigung vorgesehen'),
        ),
        migrations.AddField(
            model_name='preisangebot',
            name='mail_gesendet',
            field=models.BooleanField(default=False, verbose_name='Benachrichtigung gesendet'),
        ),
        migrations.AddField(
            model_name='preisangebot',
            name='mail_gewollt',
            field=models.BooleanField(default=True, verbose_name='Benachrichtigung vorgesehen'),
        ),
        # Muss NACH allen AddField-Schritten stehen: vorher gibt es die Spalte
        # nicht, die hier gesetzt wird.
        migrations.RunPython(_altbestand_als_erledigt_markieren, _zurueck),
    ]
