# Generated by Django 6.0.5 on 2026-09-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pagevisit_index_und_botmarkierung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fehlerereignis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kennung', models.CharField(max_length=40, unique=True)),
                ('quelle', models.CharField(max_length=100, verbose_name='Logger')),
                ('art', models.CharField(max_length=120, verbose_name='Fehlerart')),
                ('meldung', models.CharField(blank=True, max_length=500)),
                ('ort', models.CharField(blank=True, max_length=200, verbose_name='Stelle im Code')),
                ('pfad', models.CharField(blank=True, max_length=300)),
                ('methode', models.CharField(blank=True, max_length=10)),
                ('verlauf', models.TextField(blank=True, verbose_name='Stacktrace')),
                ('anzahl', models.PositiveIntegerField(default=1)),
                ('erstmals', models.DateTimeField()),
                ('zuletzt', models.DateTimeField(db_index=True)),
                ('gemeldet_bis', models.DateTimeField(blank=True, null=True)),
                ('erledigt', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Fehlerereignis',
                'verbose_name_plural': 'Fehlerereignisse',
                'ordering': ['-zuletzt'],
            },
        ),
    ]
