"""Telegram-Empfaenger, die sich selbst per Einladungslink anmelden (24.09.2026).

Nur eine neue Tabelle; der Push liest sie zusaetzlich zu TELEGRAM_CHAT_IDS.
"""
# Generated by Django 6.0.8 on 2026-09-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_push_verdacht_und_rechner_ort'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramEmpfaenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=32, unique=True, verbose_name='Chat-ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('angemeldet_am', models.DateTimeField(auto_now_add=True)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Telegram-Empfänger',
                'verbose_name_plural': 'Telegram-Empfänger',
                'ordering': ['angemeldet_am'],
            },
        ),
    ]
