"""Terminbuchung (Bauplan §5) - DREI NEUE Tabellen, keine fremde angefasst.

Die Supabase-Datenbank ist mit RTC geteilt (docs/fallen.md, "Migrationen
treffen RTC mit") - diese Migration legt ausschliesslich neue Tabellen an und
aendert keine Spalte einer bestehenden, erst recht keine einer fremden App.

Die letzte Operation legt die Standard-Wochenvorlage als echte Datenzeilen an
(Mo-Sa, 08/10/12/14/16 Uhr, aktiv) - der Vorschlag aus Bauplan §5/§9 ("Mo-Sa
08-16 Uhr"), den Oliver im Dashboard (STATS_PATH/termine/) aendern kann.
Sperren fuer konkrete Kalendertage werden bewusst NICHT vorbelegt: Ein festes
Datum in einer Migration ist in wenigen Wochen Vergangenheit und damit
entweder wirkungslos oder irrefuehrend - das entscheidet Oliver im Dashboard.
"""
# Generated by Django 6.0.8 on 2026-09-27 23:57

import django.db.models.deletion
from django.db import migrations, models


def _standardvorlage_anlegen(apps, schema_editor):
    Terminvorlage = apps.get_model('core', 'Terminvorlage')
    zeiten = ['08:00', '10:00', '12:00', '14:00', '16:00']
    for wochentag in range(6):   # 0=Montag ... 5=Samstag
        Terminvorlage.objects.get_or_create(
            wochentag=wochentag,
            defaults={'uhrzeiten': list(zeiten), 'slotlaenge': 25, 'aktiv': True},
        )


def _standardvorlage_entfernen(apps, schema_editor):
    Terminvorlage = apps.get_model('core', 'Terminvorlage')
    Terminvorlage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_telegram_empfaenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminvorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochentag', models.PositiveSmallIntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag')], unique=True, verbose_name='Wochentag')),
                ('uhrzeiten', models.JSONField(default=list, verbose_name='Uhrzeiten')),
                ('slotlaenge', models.PositiveSmallIntegerField(default=25, verbose_name='Slotlänge (Minuten)')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Terminvorlage',
                'verbose_name_plural': 'Terminvorlagen',
                'ordering': ['wochentag'],
            },
        ),
        migrations.CreateModel(
            name='Terminsperre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('uhrzeit', models.TimeField(blank=True, help_text='Leer = der ganze Tag ist gesperrt.', null=True, verbose_name='Uhrzeit')),
                ('grund', models.CharField(blank=True, default='', max_length=200, verbose_name='Grund (intern)')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Terminsperre',
                'verbose_name_plural': 'Terminsperren',
                'ordering': ['datum', 'uhrzeit'],
                'constraints': [models.UniqueConstraint(fields=('datum', 'uhrzeit'), name='unique_sperre_je_datum_uhrzeit')],
            },
        ),
        migrations.CreateModel(
            name='Besichtigungstermin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_gewollt', models.BooleanField(default=True, verbose_name='Benachrichtigung vorgesehen')),
                ('mail_gesendet', models.BooleanField(default=False, verbose_name='Benachrichtigung gesendet')),
                ('push_gesendet', models.BooleanField(default=False, verbose_name='Telegram-Push gesendet')),
                ('beginn', models.DateTimeField(verbose_name='Termin (Beginn)')),
                ('dauer', models.PositiveSmallIntegerField(default=25, verbose_name='Dauer (Minuten)')),
                ('status', models.CharField(choices=[('angefragt', 'Angefragt'), ('bestaetigt', 'Bestätigt'), ('abgesagt', 'Abgesagt')], default='angefragt', max_length=20, verbose_name='Status')),
                ('objektart', models.CharField(choices=[('Keller', 'Keller'), ('Wohnung', 'Wohnung'), ('Haus', 'Haus'), ('Gewerbe', 'Gewerbe'), ('Garten', 'Garten'), ('Scheune', 'Scheune')], max_length=20, verbose_name='Objektart')),
                ('adresse', models.CharField(blank=True, max_length=500, verbose_name='Adresse des Objekts')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('hinweis', models.TextField(blank=True, verbose_name='Hinweis')),
                ('verdacht', models.BooleanField(default=False, help_text='Grenzfall der Spam-Abwehr: gespeichert, aber ohne Mail und Push.', verbose_name='Spamverdacht')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('anfrage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termine', to='core.anfrage', verbose_name='Anfrage')),
            ],
            options={
                'verbose_name': 'Besichtigungstermin',
                'verbose_name_plural': 'Besichtigungstermine',
                'ordering': ['beginn'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'abgesagt'), _negated=True), fields=('beginn',), name='unique_aktiver_termin_slot')],
            },
        ),
        migrations.RunPython(_standardvorlage_anlegen, _standardvorlage_entfernen),
    ]
