"""GBP-Beitraege -> Aktuelles (Bauplan §7) - ein Feld an der EIGENEN Tabelle
``AktuellesPost`` (``slug``, fuer die Einzelseite) und eine neue Tabelle
``AktuellesQuelle`` fuer Herkunft/Dublettenpruefung importierter Beitraege.
Keine fremde Tabelle wird angefasst.
"""
# Generated by Django 6.0.8 on 2026-09-27 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_termine_besichtigung'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktuellespost',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=220, verbose_name='Adresse (Slug)'),
        ),
        migrations.CreateModel(
            name='AktuellesQuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quelle', models.CharField(default='gbp', max_length=20, verbose_name='Quelle')),
                ('quelle_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Kennung in der Quelle')),
                ('text_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash des Originaltexts')),
                ('original_datum', models.DateField(blank=True, null=True, verbose_name='Ursprüngliches Datum')),
                ('importiert_am', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quelle_info', to='core.aktuellespost')),
            ],
            options={
                'verbose_name': 'Aktuelles-Quelle',
                'verbose_name_plural': 'Aktuelles-Quellen',
            },
        ),
    ]
